export const SEARCH_COURSE_FAIL = "SEARCH_COURSE_FAIL";
export const SEARCH_COURSE_SUCCESS = "SEARCH_COURSE_SUCCESS";
export const SEARCH_MULTIPLE_COURSES_FAIL = "SEARCH_MULTIPLE_COURSES_FAIL";
export const SEARCH_MULTIPLE_COURSES_SUCCESS =
  "SEARCH_MULTIPLE_COURSES_SUCCESS";
export const SEARCH_MULTIPLE_COURSES_LOADING =
  "SEARCH_MULTIPLE_COURSES_LOADING";
